---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time-service
  template:
    metadata:
      labels:
        app: time-service
    spec:
      containers:
        - image: itmo-example-app:latest
          name: itmo-example-app
          imagePullPolicy: Never
          ports:
          - containerPort: 8080